# Generated by Django 4.0.6 on 2022-08-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.task')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
            bases=('base.task', models.Model),
        ),
    ]
