# Generated by Django 4.0.6 on 2022-08-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
